name: Check patches compatibility
on: push
jobs:
  build:
    runs-on: shopify-ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 16
          cache: "yarn"

      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Applying patches
        run: yarn patch-package --error-on-fail --error-on-warn
